"""add ondelete to shopping_items fks

Revision ID: 0f34ff355756
Revises: 8b3a23f78be2
Create Date: 2026-07-30 17:08:06.717472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f34ff355756'
down_revision: Union[str, Sequence[str], None] = '8b3a23f78be2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shopping_items', 'added_by_user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('shopping_items_added_by_user_id_fkey'), 'shopping_items', type_='foreignkey')
    op.drop_constraint(op.f('shopping_items_household_id_fkey'), 'shopping_items', type_='foreignkey')
    op.create_foreign_key(None, 'shopping_items', 'households', ['household_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'shopping_items', 'users', ['added_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shopping_items', type_='foreignkey')
    op.drop_constraint(None, 'shopping_items', type_='foreignkey')
    op.create_foreign_key(op.f('shopping_items_household_id_fkey'), 'shopping_items', 'households', ['household_id'], ['id'])
    op.create_foreign_key(op.f('shopping_items_added_by_user_id_fkey'), 'shopping_items', 'users', ['added_by_user_id'], ['id'])
    op.alter_column('shopping_items', 'added_by_user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
