"""add unique constraint household_user

Revision ID: 111b7d1736c5
Revises: a1205b17dbd0
Create Date: 2026-07-30 16:50:45.658022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '111b7d1736c5'
down_revision: Union[str, Sequence[str], None] = 'a1205b17dbd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_household_user', 'household_members', ['household_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_household_user', 'household_members', type_='unique')
    # ### end Alembic commands ###
