"""add expenses module

Revision ID: 61637c8c98fb
Revises: c3e7a9f21d04
Create Date: 2026-08-05 15:31:50.679269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61637c8c98fb'
down_revision: Union[str, Sequence[str], None] = 'c3e7a9f21d04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('amount_rappen', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='CHF', nullable=False),
    sa.Column('paid_by_user_id', sa.UUID(), nullable=True),
    sa.Column('expense_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount_rappen > 0', name='ck_expense_amount_positive'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paid_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_expenses_household_date', 'expenses', ['household_id', 'expense_date'], unique=False)
    op.create_table('expense_shares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('expense_id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount_rappen', sa.Integer(), nullable=False),
    sa.CheckConstraint('amount_rappen >= 0', name='ck_expense_share_amount_non_negative'),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('expense_id', 'user_id', name='uq_expense_share_user')
    )
    op.create_index('ix_expense_shares_household_user', 'expense_shares', ['household_id', 'user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_expense_shares_household_user', table_name='expense_shares')
    op.drop_table('expense_shares')
    op.drop_index('ix_expenses_household_date', table_name='expenses')
    op.drop_table('expenses')
    # ### end Alembic commands ###
