"""add_household_currency

Revision ID: a194489b8f0e
Revises: d5f2a8e3b7c1
Create Date: 2026-08-06 14:54:22.472669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a194489b8f0e'
down_revision: Union[str, Sequence[str], None] = 'd5f2a8e3b7c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('households', sa.Column('currency', sa.String(length=3), server_default='CHF', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('households', 'currency')
    # ### end Alembic commands ###
