"""add_tags_to_todos

Revision ID: e6cbf2921e48
Revises: 450c52341372
Create Date: 2026-08-07 14:06:18.217824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6cbf2921e48'
down_revision: Union[str, Sequence[str], None] = '450c52341372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('tags', sa.JSON(), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'tags')
    # ### end Alembic commands ###
