"""Maschinenlesbare Fehlercodes für API-Responses.

Konvention: detail = {"code": "<CODE>", "message": "<english fallback>"}
Frontend mapped code → i18n-Key (errors.<CODE>).
"""


class ErrorCode:
    """Fehlercodes als Konstanten."""

    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED"
    NOT_HOUSEHOLD_MEMBER = "NOT_HOUSEHOLD_MEMBER"
    INVITE_CODE_NOT_FOUND = "INVITE_CODE_NOT_FOUND"
    ALREADY_MEMBER = "ALREADY_MEMBER"
    EXPENSE_NOT_FOUND = "EXPENSE_NOT_FOUND"
    SETTLEMENT_NOT_FOUND = "SETTLEMENT_NOT_FOUND"
    USERS_NOT_IN_HOUSEHOLD = "USERS_NOT_IN_HOUSEHOLD"
    SHARES_SUM_MISMATCH = "SHARES_SUM_MISMATCH"
    SELF_SETTLEMENT_NOT_ALLOWED = "SELF_SETTLEMENT_NOT_ALLOWED"
    HOUSEHOLD_NOT_FOUND = "HOUSEHOLD_NOT_FOUND"
    NO_PARTICIPANTS = "NO_PARTICIPANTS"
    SHARES_EMPTY = "SHARES_EMPTY"
    DUPLICATE_SHARE_USER = "DUPLICATE_SHARE_USER"
    INVITE_CODE_GENERATION_FAILED = "INVITE_CODE_GENERATION_FAILED"
    CHORE_NOT_FOUND = "CHORE_NOT_FOUND"
    CHORE_WEEKDAY_REQUIRED = "CHORE_WEEKDAY_REQUIRED"
    CHORE_DAY_OF_MONTH_REQUIRED = "CHORE_DAY_OF_MONTH_REQUIRED"
    CHORE_INVALID_ROTATION = "CHORE_INVALID_ROTATION"
    CHORE_ASSIGNMENT_NOT_FOUND = "CHORE_ASSIGNMENT_NOT_FOUND"
    CHORE_WINDOW_TOO_LARGE = "CHORE_WINDOW_TOO_LARGE"
    CURRENCY_MISMATCH = "CURRENCY_MISMATCH"
    ADMIN_REQUIRED = "ADMIN_REQUIRED"
    CANNOT_REMOVE_ADMIN = "CANNOT_REMOVE_ADMIN"
    CANNOT_REMOVE_SELF = "CANNOT_REMOVE_SELF"
    TODO_NOT_FOUND = "TODO_NOT_FOUND"
    TODO_ALREADY_CLAIMED = "TODO_ALREADY_CLAIMED"
    BUDGET_NOT_FOUND = "BUDGET_NOT_FOUND"
    RECURRING_BILL_NOT_FOUND = "RECURRING_BILL_NOT_FOUND"
    BILL_ALREADY_BOOKED = "BILL_ALREADY_BOOKED"
    BILL_INACTIVE = "BILL_INACTIVE"
    INVALID_MONTH = "INVALID_MONTH"
    EVENT_NOT_FOUND = "EVENT_NOT_FOUND"
    POLL_NOT_FOUND = "POLL_NOT_FOUND"
    POLL_ALREADY_DECIDED = "POLL_ALREADY_DECIDED"
    POLL_OPTION_INVALID = "POLL_OPTION_INVALID"
    PET_NOT_FOUND = "PET_NOT_FOUND"
    FEEDING_NOT_FOUND = "FEEDING_NOT_FOUND"
    FEEDING_DUPLICATE = "FEEDING_DUPLICATE"
    FEEDING_INVALID_SLOT = "FEEDING_INVALID_SLOT"
    MEDICATION_NOT_FOUND = "MEDICATION_NOT_FOUND"
    RECIPE_NOT_FOUND = "RECIPE_NOT_FOUND"
    MEAL_PLAN_ENTRY_NOT_FOUND = "MEAL_PLAN_ENTRY_NOT_FOUND"
    MEAL_PLAN_DATE_TAKEN = "MEAL_PLAN_DATE_TAKEN"
    MEAL_PLAN_NO_RECIPE = "MEAL_PLAN_NO_RECIPE"
    POLL_TYPE_MISMATCH = "POLL_TYPE_MISMATCH"
    POLL_MEAL_DATE_REQUIRED = "POLL_MEAL_DATE_REQUIRED"
    NOTE_NOT_FOUND = "NOTE_NOT_FOUND"


def error_detail(code: str, message: str) -> dict:
    """Erzeugt ein strukturiertes detail-Objekt."""
    return {"code": code, "message": message}
